apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: microservices
data:
    CHECKOUT_SERVICE_ADDR : "checkoutservice:5050"
    CURRENCY_SERVICE_ADDR : "currencyservice:7000"
    SHIPPING_SERVICE_ADDR : "shippingservice:50051"
    CART_SERVICE_ADDR : "cartservice:7070"
    PRODUCT_CATALOG_SERVICE_ADDR : "productcatalogservice:3550"
    RECOMMENDATION_SERVICE_ADDR : "recommendationservice:8080"
    AD_SERVICE_ADDR : "adservice:9555"
    EMAIL_SERVICE_ADDR: "emailservice:5000"
    PAYMENT_SERVICE_ADDR: "paymentservice:50051"
    DISABLE_PROFILER: "true"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: microservices
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream frontend {
        server frontend.microservices.svc.cluster.local:8080;
      }

      server {
        listen 80;
        
        location / {
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        
      }
    }