name: Frontend CD

on:
  workflow_run:
    workflows: ["frontend CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Set up kubectl context
        run: |
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}

      - name: Check if Deployment Exists
        run: |
            kubectl get deployment frontend || echo "Deployment not found"
  

      - name: Deploy application to Kubernetes
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          kubectl rollout status deployment/frontend

      - name: Verify the deployment
        run: |
          kubectl get pods
