name: frontend CI

on:
  push:
    branches:
      - frontend
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.13'

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Debug KUBE_CONTEXT secret
        run: echo "KUBE_CONTEXT is set to ${{ secrets.KUBE_CONTEXT }}"

      - name: Display kubeconfig.yaml
        run: cat kubeconfig.yaml

      - name: Display available kubectl contexts
        run: |
          kubectl config get-contexts

      - name: Set up kubectl context
        run: |
          kubectl config use-context ${{ secrets.KUBE_CONTEXT }}

      - name: Deploy application to Kubernetes
        run: |
          kubectl set image deployment/frontend frontend=${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          kubectl rollout status deployment/frontend

      - name: Verify the deployment
        run: |
          kubectl get pods
